### ISSUE TITLE
BUG_01: School settings page -> invalid year value error is not thrown.

### ISSUE THREAD

**Issue by ChitraQA** [MontbitTech/WebApp-e-EdPort-LMS#119]
Steps:
1. Login the LMS http://lms.schooltimes-s.ca with Admin credentials
2. Go to the school settings page
3. Edit the value of year to 123456 and press enter

Actual: Message shows: 
Expected: Message should show: Please enter a valid year value.
![image](https://user-images.githubusercontent.com/68022354/88456422-57696880-ce9b-11ea-80c2-501e47cd4de7.png)

**Comment by krtrthbilory** [comment]
as discussed earlier will make it uneditable

**Comment by Anshumanshrivastava** [comment]
Fixed

**Comment by ChitraQA** [comment]
Fixed
