### ISSUE TITLE
BUG_04: Import Teacher > Clicking on submit without choosing file going to error page

### ISSUE THREAD

**Issue by ChitraQA** [MontbitTech/WebApp-e-EdPort-LMS#120]
Steps:
Go to the teacher tab in the admin panel
Click on Import teacher
Click submit without choosing any file

Actual: It is going to the error page
Expected: It should give a message as “choose file before submitting”
![image](https://user-images.githubusercontent.com/68022354/88456642-ca271380-ce9c-11ea-9fb6-4ec21f900fd0.png)

**Comment by Anshumanshrivastava** [comment]
Fixed

**Comment by ChitraQA** [comment]
Expected error is thrown 
![image](https://user-images.githubusercontent.com/68022354/88826034-e94bdb00-d1e5-11ea-8c90-7c5c5d7bd36b.png)
Closing the issue
