### ISSUE TITLE
BUG_07: Import Time Table >Click submit without choosing file going to error page

### ISSUE THREAD

**Issue by ChitraQA** [MontbitTech/WebApp-e-EdPort-LMS#122]
Steps:
Go to the Timetable tab in the admin panel
Click on Import timetable
Click submit without choosing any file

Actual: See log for errors
Expected: It should give a message as “choose file before submitting”

![image](https://user-images.githubusercontent.com/68022354/88457169-ea0d0600-cea1-11ea-8eaf-9b413e4e8769.png)

**Comment by krtrthbilory** [comment]
fixed

**Comment by ChitraQA** [comment]
Tested and closed in 0508
