### ISSUE TITLE
 BUG_08: Import Time table not working (unknown errors)

### ISSUE THREAD

**Issue by ChitraQA** [MontbitTech/WebApp-e-EdPort-LMS#123]
Steps: 
1.	Click on the import time table option in the admin panel 
2.	Import the time table

Actual: Error message received
Expected: Time table should have been created 

![image](https://user-images.githubusercontent.com/68022354/88457501-c13a4000-cea4-11ea-8626-bd04698ea08e.png)

**Comment by krtrthbilory** [comment]
working

**Comment by ChitraQA** [comment]
Able to upload time table now. Tracking the issue for further build/iterations.

**Comment by ChitraQA** [comment]
Able to upload time table now 
Tested and closed in 0508
