### ISSUE TITLE
BUG_16 New Classes being added to past live classes

### ISSUE THREAD

**Issue by ChitraQA** [MontbitTech/WebApp-e-EdPort-LMS#125]
Steps:

1. Login in as a teacher
2. Try to add a class in the future 

Actual:- Recording that class in past live classes dated 1 Jan
Expected:- Should be added in the upcoming lectures
![image](https://user-images.githubusercontent.com/68022354/88457987-39eecb80-cea8-11ea-9ffc-9cc037573e1d.png)

**Comment by krtrthbilory** [comment]
fixed

**Comment by ChitraQA** [comment]
Classes created on the present date are shown under live classes. No such tab available to show the classes for tomorrow. Closing this issue. 
Tested and closed in 0508
