### ISSUE TITLE
BUG_19: It is possible to a set a class in the past and still it appears in the today’s live classes tab

### ISSUE THREAD

**Issue by ChitraQA** [MontbitTech/WebApp-e-EdPort-LMS#128]
Steps:

1. Login as teacher
2. Try to add a class in the past

Actual: It is possible to add a class in the past
Expected: "It is an invalid entry" should be thrown as an error.
![image](https://user-images.githubusercontent.com/68022354/88458346-0b262480-ceab-11ea-9794-8942d0279eac.png)

**Comment by krtrthbilory** [comment]
fixed an error will occur if teacher will try to add class in past

**Comment by ChitraQA** [comment]
![image](https://user-images.githubusercontent.com/68022354/89551898-1bce8700-d829-11ea-8073-8ba014b54d54.png)
Tested and closed in 0508
