### ISSUE TITLE
BUG_20: No live class link present in the teacher join live class menu

### ISSUE THREAD

**Issue by ChitraQA** [MontbitTech/WebApp-e-EdPort-LMS#129]
Steps:

1. Login as teacher
2. Schedule a class by adding a class
3. Click on the join live link

Actual: No link found message in the alert box
Expected: The live link for a class is automatically generated. The teacher simply have click on the join live link
![image](https://user-images.githubusercontent.com/68022354/88458628-05314300-cead-11ea-8a75-9ce1a8476d14.png)

**Comment by krtrthbilory** [comment]
this also has been fixed

**Comment by krtrthbilory** [comment]
you've to add gmeet url for teacher for this to work

**Comment by ChitraQA** [comment]
Working as expected. Join live is not available when Admin has not created it for a teacher.
Join live link gets active for the teachers who have been assigned the meet URL by Admin
Tested and closed in 0508
