### ISSUE TITLE
BUG_22: Teacher > Live classes > Getting Internal error in attempt to create assignments 

### ISSUE THREAD

**Issue by ChitraQA** [MontbitTech/WebApp-e-EdPort-LMS#130]
Steps:
Log in as a teacher
Try adding an assignment 

Actual: The caller does not have permission to add the assignment message displayed
Expected: Each teacher has the ability to provide assignments to its students 
![image](https://user-images.githubusercontent.com/68022354/88459931-48dc7a80-ceb6-11ea-8bc2-e76003564e85.png)

**Comment by krtrthbilory** [comment]
this is  fixed

**Comment by krtrthbilory** [comment]
please do add a new class before testing it

**Comment by ChitraQA** [comment]
The issue is in repro in the test server 0508

Current behavior: Unable to create a new assignment for an already created class(10 A (English)) from the teacher's end

1. No topics are displayed in the dropdown, so Entered a new topic and assignment title
2. On clicking the "Next" Button, no action is performed.

Expected: Assignment should be created.
![image](https://user-images.githubusercontent.com/68022354/89530879-e4ea7800-d80c-11ea-9682-fcfd0b2d2255.png)

![image](https://user-images.githubusercontent.com/68022354/89530787-b53b7000-d80c-11ea-9367-720175423489.png)

**Comment by montbit-tech** [comment]
@ChitraQA Try logout and login, then try once immediately after login.

**Comment by montbit-tech** [comment]
Select topic or create new topic should appear as one input. The user with either select topic or create a new one. @vickyjodha please work on this part.

**Comment by ChitraQA** [comment]
> Select topic or create new topic should appear as one input. The user with either select topic or create a new one. @vickyjodha please work on this part.

**Tried logging out of the LMS and logging again, Still had the same experience: unable to create an assignment.
Able to create assignment after logging out of the browser and logging in again to the browser > then to the LMS**

@vickyjodha Please provide a fix for the "Either select a topic or enter a new topic" scenario. Currently, it is taking both inputs
![image](https://user-images.githubusercontent.com/68022354/89532022-c4bbb880-d80e-11ea-80e6-78cef95d3fa0.png)

**Comment by montbit-tech** [comment]
@ChitraQA still facing this issue? I believe this was fixed, right?

**Comment by ChitraQA** [comment]
@montbit-tech getting internal Error, 
@krtrthbilory Please Note
The assignment gets created in the classroom. but this error is thrown in LMS
![image](https://user-images.githubusercontent.com/68022354/91433353-cbbf6f00-e880-11ea-8748-15c25d93b63e.png)
