### ISSUE TITLE
No option to see "All help tickets"

### ISSUE THREAD

**Issue by ChitraQA** [MontbitTech/WebApp-e-EdPort-LMS#131]
Steps:
Step 1: 
1.1 Login as Teacher
1.2 Go to today's live classes and click on the help button.
Step 2:
2.1. Log in as admin
2.2. Go to help tickets page
2.3. Click on the select category dropdown. observe the options.

Actual: There is no option available that shows the raised help ticket. When the"select category" option is selected from the drop-down. The whole list of tickets is displayed.

Expected: Help tickets page should have the option to show the category of live class help tickets. Or, should have the option to show all the help tickets.

![image](https://user-images.githubusercontent.com/68022354/88460071-31ea5800-ceb7-11ea-8f0a-728edf0ddfda.png)

**Comment by krtrthbilory** [comment]
fixed

**Comment by ChitraQA** [comment]
Show all option is available now. It shows all the help tickets under all categories. 
![image](https://user-images.githubusercontent.com/68022354/88522383-e3060500-d013-11ea-8da0-41216429ff41.png)

Closing the issue.
