### ISSUE TITLE
Teacher is unable to create a class

### ISSUE THREAD

**Issue by ChitraQA** [MontbitTech/WebApp-e-EdPort-LMS#132]
Steps: 
1. Log in as a teacher (id: paras@schooltimes-s.ca password: 9996721897)
2. Today's live classes page > Add classes
3. click on Select class dropdown

**Actual: No classes are shown even if the teacher has been assigned a class.
Expected:  Classes assigned to this teacher should be visible in the drop-down options.**
![image](https://user-images.githubusercontent.com/68022354/88463526-feb4c280-ced0-11ea-88ca-8dcdff7fbb53.png)

**Comment by krtrthbilory** [comment]
there is no datain timetable for paras rawat as I can see it depends on timetable being set @raiaman15

**Comment by ChitraQA** [comment]
> there is no datain timetable for paras rawat as I can see it depends on timetable being set @raiaman15

Teacher is able to create a class now. 
New Related ISSUE 
https://github.com/MontbitTech/WebApp-e-EdPort-LMS/issues/133
