### ISSUE TITLE
Teacher > New classes created from Teacher's end are not visible in the LMS portal

### ISSUE THREAD

**Issue by ChitraQA** [MontbitTech/WebApp-e-EdPort-LMS#133]
Steps:

1. Log in as a teacher
2. Live classes -> Add classes > Create a class for a future date
3. Observe that the class created successfully.

Actual: The created class is not shown anywhere in the portal.
Expected: All the created classes should be shown to the teacher.

**Comment by krtrthbilory** [comment]
I see that you've created a class for 28th and today is 27th there is no future classes tab so the you've created will be there tomorrow if you wanna add a class and see if it's getting added please add it with today's date @ChitraQA  NOT A BUG

**Comment by ChitraQA** [comment]
> I see that you've created a class for 28th and today is 27th there is no future classes tab so the you've created will be there tomorrow if you wanna add a class and see if it's getting added please add it with today's date @ChitraQA NOT A BUG

Not a bug
