### ISSUE TITLE
Teacher > Today's live classes page > Selecting a topic is not showing the content links automatically

### ISSUE THREAD

**Issue by ChitraQA** [MontbitTech/WebApp-e-EdPort-LMS#134]
Steps:
1. Log in as admin.
2. Add CMS topics for a class
3. Assign the class to a particular teacher.
Log in as a teacher
1. Select CMS topic from Live classes

Actual: The content links are not showing up automatically. (they are shown after reloading the page)
Expected: The content links should be shown as soon as the topic is selected by the teacher without the need to reload the page.

**Comment by Anshumanshrivastava** [comment]
fixed

**Comment by ChitraQA** [comment]
Link gets shown automatically. 
![image](https://user-images.githubusercontent.com/68022354/89552661-1887cb00-d82a-11ea-9606-e31aeba918dc.png)
Tested and closed in 0508
