### ISSUE TITLE
BUG_27: Back button functionality in LMS admin is Broken

### ISSUE THREAD

**Issue by ChitraQA** [MontbitTech/WebApp-e-EdPort-LMS#137]
### Steps:

1. Open the admin login
2. The back button on the sidebar is meant for the collapsing and expanding of the sidebar

Actual: The functionality of the back button is missing. The direction of the back button changes when the side panel is hidden in reduced window size. But, it fails to open the sidebar in a minimized window.
Expected: Back button should trigger opening and collapse of the sidebar

### NOTE: Issue found while reducing the window size of the chrome browser.

Reduced window screenshot:
![image](https://user-images.githubusercontent.com/68022354/88796955-2e5d1680-d1c0-11ea-98d9-6ad803884642.png)

Maximized Screenshot:
![image](https://user-images.githubusercontent.com/68022354/88797038-4f256c00-d1c0-11ea-9c62-b59a020366ef.png)

**Comment by vickyjodha** [comment]
done
