### ISSUE TITLE
Admin > Help Tickets > Closed date and time should be included.

### ISSUE THREAD

**Issue by ChitraQA** [MontbitTech/WebApp-e-EdPort-LMS#140]
1. Upon closing the help ticket with comments, the Date and time of closing should be included along with the created date section.
2. Tenure or duration of the help ticket shall also be displayed for the future reference of Admin.

![image](https://user-images.githubusercontent.com/68022354/88821793-b3582800-d1e0-11ea-95cc-e10edaa0295b.png)

**Comment by krtrthbilory** [comment]
fixed

**Comment by ChitraQA** [comment]
Fixed
![image](https://user-images.githubusercontent.com/68022354/89555160-56d2b980-d82d-11ea-990c-da40f1fae2e1.png)

Tested and closed in 0508
