### ISSUE TITLE
Admin > Help tickets > Unable to change the status of help ticket

### ISSUE THREAD

**Issue by ChitraQA** [MontbitTech/WebApp-e-EdPort-LMS#142]
Steps:
1. Log in as Admin
2. Go to help tickets page
3. Select a category to display the help tickets.
4. Change the status of help ticket from pending to Closed or Pending to In progress.
5. Reload the page

Actual: On reloading the page the Status reverts back to pending automatically.
Expected: the status should be changed from "Pending to in progress" or "pending to closed" successfully.

Changed the status
![image](https://user-images.githubusercontent.com/68022354/88823300-8ad12d80-d1e2-11ea-9e80-2900d664743e.png)

Clicked outside the dropdown to save it
![image](https://user-images.githubusercontent.com/68022354/88823329-93296880-d1e2-11ea-8a4d-312c5156dcdf.png)

Reloaded the page
![image](https://user-images.githubusercontent.com/68022354/88823362-9f152a80-d1e2-11ea-9ad7-a4625d803dad.png)

**Comment by krtrthbilory** [comment]
fixed

**Comment by ChitraQA** [comment]
The status of help tickets can be changed successfully. Closing the issue
