### ISSUE TITLE
Teacher > Live Classes > Sort out the classes, Upcoming classes in the day should be shown first

### ISSUE THREAD

**Issue by ChitraQA** [MontbitTech/WebApp-e-EdPort-LMS#144]
Expected:
Teacher > Live classes (at 1 pm)
Classes that are coming later in the day like 1 pm onwards should be shown at first
Class at 1:30 pm
Class at 2:00  pm
..
..
Class at 6:00 pm (End of day)
Class at 10:00 am (Starting of the day)
Class at 11:00 am 
Class at 12:00 pm

**Comment by Anshumanshrivastava** [comment]
fixed
