### ISSUE TITLE
Teacher > Past Live classes > Sort out the classes, show classes up to 1 week (recent past first)

### ISSUE THREAD

**Issue by ChitraQA** [MontbitTech/WebApp-e-EdPort-LMS#146]
Sort the past live classes to show the recent past first.
For example, the time now: 1 pm
Past live classes sequence:
Class at 12 pm today
Class at 10 am today
Class at 5 pm yesterday
Class at 3 pm yesterday
Class at 12 pm yesterday, etc

**Comment by krtrthbilory** [comment]
today's classes are already there in today's live classes past classes should be start from yesterday as discussed

**Comment by krtrthbilory** [comment]
done
