### ISSUE TITLE
Admin> Add student Details > Change the notify checkbox text to "SMS" notification for student

### ISSUE THREAD

**Issue by ChitraQA** [MontbitTech/WebApp-e-EdPort-LMS#147]
Log in as admin
Add student details page
Enhancement: 
Change the notify checkbox text to **SMS notification for student**
![image](https://user-images.githubusercontent.com/68022354/88899261-78e79d00-d26b-11ea-9bb8-2e34ff2330a7.png)

**Comment by vickyjodha** [comment]
done

**Comment by ChitraQA** [comment]
![image](https://user-images.githubusercontent.com/68022354/89550516-52a39d80-d827-11ea-8620-f7c197643125.png)
Tested and closed in 0508
