### ISSUE TITLE
LMS > PORT UI > Add "powered by e-EdPort in the bottom of sidebar.

### ISSUE THREAD

**Issue by ChitraQA** [MontbitTech/WebApp-e-EdPort-LMS#149]
for example:
![image](https://user-images.githubusercontent.com/68022354/88901947-214b3080-d26f-11ea-969d-f4723d95ecc2.png)

**Comment by ChitraQA** [comment]
**Please change the 'By' to 'by' and 'e-Edport' to 'e-EdPort' as shown below
 "Powered by e-EdPort"**

![image](https://user-images.githubusercontent.com/68022354/88919564-f1108b80-d288-11ea-9f34-4182bdc1b4ee.png)

**Comment by vickyjodha** [comment]
done

**Comment by ChitraQA** [comment]
Tested and closed in 0508
