### ISSUE TITLE
Mail/SMS to be sent to teacher on status change of help ticket by Admin (Should include the comments in email)

### ISSUE THREAD

**Issue by ChitraQA** [MontbitTech/WebApp-e-EdPort-LMS#150]
Expected email:
The status of your help ticket has been changed to closed.
Admin comments: "******************"

Expected text message:
The status of your help ticket has been changed to closed.

**Comment by krtrthbilory** [comment]
fixed

**Comment by ChitraQA** [comment]
Fixed and closed in 0508
