### ISSUE TITLE
Warning/Error messages on all the pages should be understandable to novice person.

### ISSUE THREAD

**Issue by ChitraQA** [MontbitTech/WebApp-e-EdPort-LMS#153]
Warning messages on all pages should be understandable to a novice person.
Should also include the steps to remove the error wherever possible.
**For example: 
The name field should include letters only.**

**Comment by krtrthbilory** [comment]
it would be better if you name the error and place

**Comment by montbit-tech** [comment]
@krtrthbilory I think we all are aware that all error messages are not up to mark. Take this one as a big task and check this thoroughly on each page in code, it will be easier to find the error messages in code rather than on each page and then testing in what cases, which ones appear.

**Comment by krtrthbilory** [comment]
a lot many of them are already been changed I am talking about if you get any other and it's not that easy to fin all the errors in code as files are always more than the pages you see on frontend

**Comment by ChitraQA** [comment]
Getting this error while uploading CSV for classroom
Caught the error when: The file was uploaded successfully already. Tried to upload the same file again.
Error: Teacher details processed, Please check logs for detailed error, errors in rows - 1

![image](https://user-images.githubusercontent.com/68022354/89545332-d6a65700-d820-11ea-9011-2393965422ba.png)
