### ISSUE TITLE
Admin > Add CMS link > Youtube format shows invalid

### ISSUE THREAD

**Issue by ChitraQA** [MontbitTech/WebApp-e-EdPort-LMS#156]
Log in as admin
Add CMS Link
Select class, subject, topic, and copy a valid youtube URL 
for example https://www.youtube.com/watch?v=hZyz78xlYfM 

Actual: The below message is shown: The youtube format is invalid.
Expected: The cms topic should get uploaded 

![image](https://user-images.githubusercontent.com/68022354/88909227-7a6b9200-d278-11ea-9f17-5d57f8338f7a.png)

**Comment by ChitraQA** [comment]
Youtube link is not getting accepted, I tried with multiple valid youtube URLs
NOTE: On removing the youtube URL, the CMS got submitted successfully. (10 A English)
![image](https://user-images.githubusercontent.com/68022354/88909858-4644a100-d279-11ea-9538-4db61a822c1e.png)

**Comment by Anshumanshrivastava** [comment]
fixed

**Comment by ChitraQA** [comment]
Not fixed in 0508. To be tested in further builds.

> We are calling the current build 0508 to easily maintain and track the bugs in the future, 0508 stands for 05 August. 
We will name the build based on the date we will get the staging for the test server and track the fixes accordingly.

**Comment by krtrthbilory** [comment]
I checked it's getting added with the same youtube url you've provided in the bug description

**Comment by ChitraQA** [comment]
Tested and closed in 0508
