### ISSUE TITLE
Teacher> replace the content links under select topic into icons instead of texts.

### ISSUE THREAD

**Issue by ChitraQA** [MontbitTech/WebApp-e-EdPort-LMS#157]
1. Log in as a teacher
2. Live classes tab
3. On selecting a topic from drop-down (Related Issue #134) 

Enhancement:
The Content links that appear should be a form of icons rather than text buttons.

![image](https://user-images.githubusercontent.com/68022354/88910403-0f22bf80-d27a-11ea-9109-857bf3898aea.png)

**Comment by Anshumanshrivastava** [comment]
fixed

**Comment by vickyjodha** [comment]
done

**Comment by ChitraQA** [comment]
Tested and closed in 0508
