### ISSUE TITLE
Teacher > Edit class details > Make the join link un-editable as a note in the bottom in the frame.

### ISSUE THREAD

**Issue by ChitraQA** [MontbitTech/WebApp-e-EdPort-LMS#158]
Log in as a teacher
Edit class details for a class under Today's live classes

Enhancement:
### The frame should include:
> Description : Class description (Editable)
> Notify Students : (Editable)
> Save Class  | Cancel
> Join Live link: (uneditable)

![image](https://user-images.githubusercontent.com/68022354/88911652-c23fe880-d27b-11ea-9739-f67fdeb1f219.png)

**Comment by vickyjodha** [comment]
done

**Comment by ChitraQA** [comment]
Tested and closed in 0508
