### ISSUE TITLE
Admin > Notification > Add a functionality of the notification Icon

### ISSUE THREAD

**Issue by ChitraQA** [MontbitTech/WebApp-e-EdPort-LMS#159]
Step1:
1. log in a teacher
2. Generate a help ticket

Step 2:
1. Log in as admin
2. Observe that the notification Icon is changing colors
3. Click on the notification icon 

**Actual: Page reloads
Expected: Help tickets page should open and the recently generated ticket should be shown under the Help tickets**

![image](https://user-images.githubusercontent.com/68022354/88915441-e7cff080-d281-11ea-8f08-8cbee52b72a1.png)
.

**Comment by krtrthbilory** [comment]
fixed

**Comment by ChitraQA** [comment]
Expected: Help tickets page should open and the help tickets should be shown under the Help tickets
Please fix #193 to close this issue
Tested in 0508

**Comment by ChitraQA** [comment]
Tested and closed in 0908
