### ISSUE TITLE
Admin > CMS topics > UI improvement > Change the link headers to YouTube, Wiki, etc.

### ISSUE THREAD

**Issue by ChitraQA** [MontbitTech/WebApp-e-EdPort-LMS#160]
Enhancement:
The change should be corresponding to the URLs uploaded while creating the CMS.
![image](https://user-images.githubusercontent.com/68022354/88918098-8b230480-d286-11ea-919c-83a0591bd3a8.png)

![image](https://user-images.githubusercontent.com/68022354/88917863-19e35180-d286-11ea-9f75-49b0d721f390.png)

**Comment by Anshumanshrivastava** [comment]
fixed

**Comment by ChitraQA** [comment]
Fixed and closed in 0508
![image](https://user-images.githubusercontent.com/68022354/89517488-5f100200-d7f7-11ea-95ad-f38c1a9d07da.png)
