### ISSUE TITLE
Admin > Classes > Import classes > Supply a sample Class file format to be downloaded

### ISSUE THREAD

**Issue by ChitraQA** [MontbitTech/WebApp-e-EdPort-LMS#161]
steps:
1. Log in as Admin
2. Go to classes tab
3. Click on import Class

Enhancement:
A download sample file option should be available for importing class in a valid format.

**Comment by krtrthbilory** [comment]
fixed

**Comment by ChitraQA** [comment]
Tested in 0508
A sample class file is available. However, it does not match the exported file (downloaded) from LMS
Tracking #201 for the issue.
Closing this issue.
