### ISSUE TITLE
Admin > Classes > All the classes should be shown after opening the tab at first.

### ISSUE THREAD

**Issue by ChitraQA** [MontbitTech/WebApp-e-EdPort-LMS#162]
Steps:
1. log in as admin
2. Go to classes tab

Actual: No classes are shown when the tab is opened for the first time

**Expected: on opening the classes tab: All the classes sorted by Class 1 to 12 (Alphabetical and numerical order) should be shown.
On selecting the filters from drop-down the selected classes should be shown**

**Enhancement:  Include an option to show all the classes, i.e. Include "All" in the classes dropdown (similar to the Select section drop-down) This option will show all the classes and sections of all the classes as it should show when the classes tab is opened for the first time.**

![image](https://user-images.githubusercontent.com/68022354/88931245-34272a80-d29a-11ea-8913-592dd4cebccf.png)

**Comment by Anshumanshrivastava** [comment]
done

**Comment by ChitraQA** [comment]
Tested and closed in 0508
