### ISSUE TITLE
Admin > Time Table > UI > Move the Delete and View/Download button to the right side of the page

### ISSUE THREAD

**Issue by ChitraQA** [MontbitTech/WebApp-e-EdPort-LMS#164]
Admin > time table> Enhancements:
1. Dropdown for Selecting class and section should be placed on the left side of the page
2. "Delete All" button text should be changed to "Delete"
3. Delete button should be placed on the right side of the page
4. Download/View button should be placed on the right side of the page.

![image](https://user-images.githubusercontent.com/68022354/88934528-5a4ec980-d29e-11ea-9773-9818c495af8c.png)

**Comment by ChitraQA** [comment]
Apply similar UI changes to the Student's page

1. Dropdown for Selecting class and section should be placed on the left side of the page
2. "Delete All Selected" button text should be placed on the right side of the page
3. "Export CMS details" button should be changed to "Export Student details"
4. Export Student details button should be placed on the right side of the page.


![image](https://user-images.githubusercontent.com/68022354/88936294-62a80400-d2a0-11ea-90b7-044ecbf8d9f8.png)

**Comment by vickyjodha** [comment]
done

**Comment by ChitraQA** [comment]
Tested and closed in 0508
