### ISSUE TITLE
Admin > School settings > Unable to upload school logo

### ISSUE THREAD

**Issue by ChitraQA** [MontbitTech/WebApp-e-EdPort-LMS#165]
Admin> school settings 
1. select a School logo
2. Click on Save

Actual: The below error is shown and the page is crashed
Expected: school logo should be changed successfully.
![bug](https://user-images.githubusercontent.com/68022354/89030524-4793cd80-d34e-11ea-9abc-6bdb1702821d.PNG)

**Comment by krtrthbilory** [comment]
working

**Comment by vickyjodha** [comment]
done

**Comment by ChitraQA** [comment]
Tested and closed in 0508
