### ISSUE TITLE
Admin . Students page> Show all students topics when the page  is opened at first

### ISSUE THREAD

**Issue by ChitraQA** [MontbitTech/WebApp-e-EdPort-LMS#167]
Steps:
1. Log in as Admin
2. Go to students page

**Actual: No students are shown unless the filter is selected
Expected: show all the students when the page is opened at first.
Also, Add the select all button In the filter option to show all students whenever required.**

![image](https://user-images.githubusercontent.com/68022354/89033169-d820dc80-d353-11ea-9a00-7f13dd500f27.png)

**Comment by Anshumanshrivastava** [comment]
done

**Comment by ChitraQA** [comment]
Tested and closed in 0508
