### ISSUE TITLE
Admin > CMS Topics page> Include "Show all" filter option

### ISSUE THREAD

**Issue by ChitraQA** [MontbitTech/WebApp-e-EdPort-LMS#168]
Steps:
1. Log in as Admin
2. Go to CMS topics page
3. Select a filter for class and section

**Actual: No option available to remove the selected filter and show all the CMS topics
Expected: The "Show all" button In the filter option to show all CMS topics whenever required.**

![image](https://user-images.githubusercontent.com/68022354/89033504-83ca2c80-d354-11ea-8a6b-95a2433b8eb5.png)

**Comment by Anshumanshrivastava** [comment]
done
