### ISSUE TITLE
Delete popup > Make the Type delete field as mandatory

### ISSUE THREAD

**Issue by ChitraQA** [MontbitTech/WebApp-e-EdPort-LMS#170]
Click on delete on any of the following pages 
1. Teacher
2. Classes
3. Student
4. Help tickets
5. CMS topics (#169 ) (to add the functionality in here as well)

Expected: The text field should be **mandatory**.
Actual: The Delete button is active even if there is no input in the text field.

![image](https://user-images.githubusercontent.com/68022354/89033843-56ca4980-d355-11ea-99ca-5165348a7551.png)

**Comment by vickyjodha** [comment]
done

**Comment by ChitraQA** [comment]
Tested and closed in 0508
