### ISSUE TITLE
Admin > Edit Time table - teachers are not shown in the drop-down

### ISSUE THREAD

**Issue by ChitraQA** [MontbitTech/WebApp-e-EdPort-LMS#172]
Admin > Time table
Select a time table class and section
Edit teacher for a cell

Actual: no option available
Expected: All teachers names should be shown to select one from.

**Comment by krtrthbilory** [comment]
The functionality works when there is any teachers available at selected time please recheck once and let me know

**Comment by ChitraQA** [comment]
Works as expected in the 0908 build.. closing issue
