### ISSUE TITLE
Admin > Teachers > Duplicate GMeet links are getting assigned to multiple teachers

### ISSUE THREAD

**Issue by ChitraQA** [MontbitTech/WebApp-e-EdPort-LMS#173]
Steps:
1. Log in admin
2.  Go to teachers tab
3. Edit teachers /Insert Gmeet URL
4. Insert the same URL for 2 teachers

Actual: Gmeet URL added successfully for 2 teachers.
Expected: Error should be thrown when duplicate URL is entered for teachers.

![image](https://user-images.githubusercontent.com/68022354/89097410-4caf5600-d3fc-11ea-95b2-ba9f3767dd79.png)

![image](https://user-images.githubusercontent.com/68022354/89097422-66e93400-d3fc-11ea-8697-3ed25b9fcfa4.png)

**Comment by Anshumanshrivastava** [comment]
done

**Comment by ChitraQA** [comment]
Tested and closed in 0908
