### ISSUE TITLE
Admin > Time table > "Reload today's timetable for all teachers" link is opening a new tab

### ISSUE THREAD

**Issue by ChitraQA** [MontbitTech/WebApp-e-EdPort-LMS#175]
1. Log in as Admin
2. Time table > Select a class and section 
3.  Click on Reload today's timetable for all teachers

Actual: Error is shown No record found on class timing.
Expected: Reload successfully.
![image](https://user-images.githubusercontent.com/68022354/89736886-74508f00-da8a-11ea-8e5e-c368e8af030c.png)

**Comment by krtrthbilory** [comment]
done

**Comment by ChitraQA** [comment]
Tested and closed in 0508

**Comment by ChitraQA** [comment]
This issue is repro in the test server 0908

**Comment by krtrthbilory** [comment]
today is sunday please check tomorrow
