### ISSUE TITLE
Admin > UI > Import and export Icons are opposite.

### ISSUE THREAD

**Issue by ChitraQA** [MontbitTech/WebApp-e-EdPort-LMS#176]
Import icons should be inwards/inwards
export icons should be outwards/upwards
Please apply this in all the pages where we have these buttons.
![image](https://user-images.githubusercontent.com/68022354/89102201-6bc1de00-d424-11ea-8a57-ae5b25651a8c.png)

**Comment by vickyjodha** [comment]
done

**Comment by ChitraQA** [comment]
Tested and closed in 0908
