### ISSUE TITLE
Admin > Import teachers through csv throwing Authentication error

### ISSUE THREAD

**Issue by ChitraQA** [MontbitTech/WebApp-e-EdPort-LMS#177]
1. log in as Admin in LMS
2. Go to teacher's page
3. Click on import teachers
4. Select a valid file with the teacher(s) details.

**Expected: Teacher(s) should be uploaded successfully.
Actual: On selecting the attached file, the attached authentication error is thrown.**

![image](https://user-images.githubusercontent.com/68022354/89102311-82b50000-d425-11ea-8832-42af28182f83.png)

![image](https://user-images.githubusercontent.com/68022354/89102308-7a5cc500-d425-11ea-8d28-13516d017092.png)

**Comment by ChitraQA** [comment]
Managed to get a message shown below
![image](https://user-images.githubusercontent.com/68022354/89102627-c1988500-d428-11ea-91da-ddbbfbc92244.png)
for the file
![image](https://user-images.githubusercontent.com/68022354/89102661-0fad8880-d429-11ea-9ff8-07349629f960.png)

**But the teacher did not get uploaded. So still unable to upload teachers through CSV**

**Comment by krtrthbilory** [comment]
fixed

**Comment by ChitraQA** [comment]
Tested and closed in 0908
