### ISSUE TITLE
Admin > Student > Add Student with email and phone 

### ISSUE THREAD

**Issue by ParasRawat** [MontbitTech/WebApp-e-EdPort-LMS#178]
Steps: 
1. Login in as an Admin
2. Go to students tab
3. Add students with any domain and phone number 
4. Students with any domain are added 

Actual: Student with any domain are being added here 
Expectations: Students should be restricted to provide their google id in order to join the class 

![image](https://user-images.githubusercontent.com/33607689/89103655-f9a3c600-d430-11ea-8c85-70d448aa8111.png)

**Comment by krtrthbilory** [comment]
done

**Comment by ChitraQA** [comment]
fixed in the test server 0508

![image](https://user-images.githubusercontent.com/68022354/89459082-bbd2d480-d785-11ea-8869-6e79662981c7.png)
