### ISSUE TITLE
Admin > Import teacher's sample file is not same as exported file from the LMS

### ISSUE THREAD

**Issue by ChitraQA** [MontbitTech/WebApp-e-EdPort-LMS#179]
The column names are different. Please make the same.

![image](https://user-images.githubusercontent.com/68022354/89103773-fd841800-d431-11ea-8360-ec8d1aa08c5b.png)

**Comment by Anshumanshrivastava** [comment]
fixed

**Comment by ChitraQA** [comment]
Fixed in the test server 0508
