### ISSUE TITLE
Admin > Students > Duplicate Students 

### ISSUE THREAD

**Issue by ParasRawat** [MontbitTech/WebApp-e-EdPort-LMS#181]
Steps 
1. Log in as admin
2. Add a student 
3. Add that same student again 

Actual: Duplicate students are being added 
Expected: Only 1 student per email and password

![image](https://user-images.githubusercontent.com/33607689/89104458-278c0900-d437-11ea-93db-0961b90f90e8.png)

**Comment by krtrthbilory** [comment]
done

**Comment by ChitraQA** [comment]
Fixed in the test server 0508
> Actual behavior is as expected: Duplicate Student's name is allowed, throwing error for the duplicate phone number and email.
