### ISSUE TITLE
Admin > Time Table > Edit Schedule 

### ISSUE THREAD

**Issue by ParasRawat** [MontbitTech/WebApp-e-EdPort-LMS#182]
Steps 
1. Log in using admin
2. Upload a time table 
3. Make changes in that time table 
4. Login as a teacher 

Actual: No changes are visible in the teachers view. 
Expected: The time table changes should be reflected in the teachers tab 

![image](https://user-images.githubusercontent.com/33607689/89107247-44333b80-d44d-11ea-9884-245f1c923e1c.png)

**Comment by ChitraQA** [comment]
Fixed
