### ISSUE TITLE
Admin > Unable to view the time table which is uploaded successfully.

### ISSUE THREAD

**Issue by ChitraQA** [MontbitTech/WebApp-e-EdPort-LMS#192]
> Issue found in test server 0508 (5th August)

Steps:

1. Log in using admin
2. Upload a time table -> time table uploaded successfully
3. Go to the time table page and select the Class and section (for which you have uploaded the time table)

Actual: Time table is not visible. Although the classes are added in the teacher's portal
Expected: Time table should be Visible
![image](https://user-images.githubusercontent.com/68022354/89452187-e10e1580-d77a-11ea-8a90-7f80bff24680.png)
![image](https://user-images.githubusercontent.com/68022354/89452259-fc792080-d77a-11ea-8ca2-1d8c1716962a.png)

![image](https://user-images.githubusercontent.com/68022354/89452034-b0c67700-d77a-11ea-8a94-a240a0b2fc72.png)

**Comment by krtrthbilory** [comment]
this was a permission issue on server got fixed

**Comment by ChitraQA** [comment]
fixed in 0508.
Closing the issue.
