### ISSUE TITLE
ADMIN > CLASSROOM > IMPORT CLASSROOM 

### ISSUE THREAD

**Issue by ParasRawat** [MontbitTech/WebApp-e-EdPort-LMS#196]
Steps:
1. Log in as admin
2. Go to classroom tab and click import classroom
3. Import classroom

Actual: Classrooms are created but no acknowledgement received rather error message visible 
Expected: Should get success acknowledgement after the import 

![image](https://user-images.githubusercontent.com/33607689/89504730-21ef4400-d7e6-11ea-82ee-babc0058f5b9.png)

**Comment by krtrthbilory** [comment]
there are some errors while uploading you gotta check here : https://lms.schooltimes-s.ca/logs

**Comment by krtrthbilory** [comment]
some of the classrooms has been added but some have errors that's why the error message

**Comment by ChitraQA** [comment]
Fixed
