### ISSUE TITLE
Admin > Classroom > Only Already existing classes are shown while manually adding classroom

### ISSUE THREAD

**Issue by ChitraQA** [MontbitTech/WebApp-e-EdPort-LMS#197]
Steps:
1. Admin > Classroom
2. Create a classroom

Actual: 
1. Only imported classes (through CSV) are available in the dropdown in the add classroom section.
2. NO new classrooms can be created manually from the add classroom tab.

Expected: 
1. Admin should be able to create new classrooms manually from the add classroom option
2. All the classes, sections and subjects should be available in the add classroom section (in the dropdowns to select)

![image](https://user-images.githubusercontent.com/68022354/89506316-8dd2ac00-d7e8-11ea-894f-d348cbd9e126.png)
![image](https://user-images.githubusercontent.com/68022354/89506721-29fcb300-d7e9-11ea-8684-5eab7cade11b.png)

**Comment by krtrthbilory** [comment]
need to add more classes from database backend as I've  told you on slack ask raman to do it as I don't have access to database.
you may ask him to some classes for testing. NOT A BUG

**Comment by ChitraQA** [comment]
@Raman-montbit Please do the needful.

**Comment by Raman-montbit** [comment]
@ChitraQA  added claases and subjects in database manually.

**Comment by ChitraQA** [comment]
As discussed, the classroom can be created from the backend and through CSV for testing. 
Closing this issue.
Tested and closed in 0508
