### ISSUE TITLE
ADMIN > REDIRECTION TO LOGIN AFTER SESSION EXPIRE 

### ISSUE THREAD

**Issue by ParasRawat** [MontbitTech/WebApp-e-EdPort-LMS#199]
Actual: LMS automatically takes the teacher or admin to login page after session expiration. This happens mainly when we are trying a functionality like upload a time table, create a class etc

Expected: Token should be automatically refreshed in the background and the LMS user teacher/admin should remain logged in.
 Session expiration and refresh details should not be visible to the user.
![image](https://user-images.githubusercontent.com/33607689/89516757-77335180-d7f6-11ea-8e7c-ee06698d640b.png)

**Comment by krtrthbilory** [comment]
fixed
