### ISSUE TITLE
Admin -> School settings -> PAGE UI -> Items' names format is not as expected 

### ISSUE THREAD

**Issue by ChitraQA** [MontbitTech/WebApp-e-EdPort-LMS#20]
The fields under the Item column are all in small alphabet letters with no space between the two words : 
Mail From is shown as "mailfrom"
School Name is shown as "schooname"
School Logo is shown as "schoologo"
School Address is shown as "schooaddress"
![image](https://user-images.githubusercontent.com/68022354/86946545-27fef000-c168-11ea-99c1-3a0f104d9945.png)

**Comment by krtrthbilory** [comment]
database seeding issue not a coding error remind raman and aman about they will be carefull about putting space while adding data into the table

**Comment by montbit-tech** [comment]
@vickyjodha will fix this in his UI branch.

**Comment by krtrthbilory** [comment]
this data is directly comming from database better to fix data and writing frontend logic for this
