### ISSUE TITLE
Admin > classroom > sample file is not same as exported file from the LMS

### ISSUE THREAD

**Issue by ChitraQA** [MontbitTech/WebApp-e-EdPort-LMS#201]
The column names are different. Please make them same. 

![image](https://user-images.githubusercontent.com/68022354/89528858-63451b00-d809-11ea-9656-4c15e2de0d06.png)

**Comment by krtrthbilory** [comment]
fixed

**Comment by ChitraQA** [comment]
Tested the fix. Closing the Issue
