### ISSUE TITLE
Admin > Content > The exported file is incorrect

### ISSUE THREAD

**Issue by ChitraQA** [MontbitTech/WebApp-e-EdPort-LMS#203]
Steps:
1. log in as Admin in LMS
2. Go to Content page
3. Select the FIlter 
4. Click on Export content

Actual: the file that gets downloaded is not showing the links. It has incorrect column headers.
Expected: the file should have the links to the contents. The exported file columns should be same as the columns shown in LMS (except for the Action column Edit | Delete)

![image](https://user-images.githubusercontent.com/68022354/89547131-02c2d780-d823-11ea-9ccd-933f74a902f9.png)

![image](https://user-images.githubusercontent.com/68022354/89547247-25ed8700-d823-11ea-9e4b-a91a5b3dbe18.png)

> Issue found in 0508

**Comment by krtrthbilory** [comment]
fixed
