### ISSUE TITLE
Admin > Content > The exported file is not same as sample file downloaded from LMS

### ISSUE THREAD

**Issue by ChitraQA** [MontbitTech/WebApp-e-EdPort-LMS#204]
The issue is related to #203 
Steps:

1. log in as Admin in LMS
2. Go to Content page
3. Select the FIlter
4. Click on Export content > FIle gets downloaded.
5. Click on Import Content
6. Download the sample file

**Actual: The two files are not having the same format (The column names are different.)
Expected: The exported file should be formatted exactly same as the sample file downloaded.** 
Below is the Sample file
![image](https://user-images.githubusercontent.com/68022354/89547858-e96e5b00-d823-11ea-890c-9402f219f7dc.png)
Below is the exported file
![image](https://user-images.githubusercontent.com/68022354/89548135-45d17a80-d824-11ea-8082-9dc7fb9cd159.png)

> Issue is found in 0508

**Comment by krtrthbilory** [comment]
fixed
