### ISSUE TITLE
ADMIN > MISSING ATOMICITY PROPERTY 

### ISSUE THREAD

**Issue by ParasRawat** [MontbitTech/WebApp-e-EdPort-LMS#207]
Actual: Sometimes it is observed that a process like uploading teachers csv, or class csv etc is partially completed and errors are shown for the rest of the part at same time. However, only the error message is visible to the end user and he has no idea that partial data from the csv filed has already been processed and added to our system. When user corrects the mentioned error in the csv and tries to upload the file again, then he observes duplicate entity errors.

This happened with me in two scenarios today

1. I tried importing classrooms through csv files, certain subjects were added from the file in the system and some had errors but as a user I only received an error message. So I corrected the errors and then tried uploading the same subjects using csv file assuming that previous upload didn't work, here I fell into duplicate entries error as visible in the log

2. I tried uploading students through csv and certain columns had wrong email id and some had the right. The right rows were processed and added in the system but error message was shown after the process, so I assumed the process did not complete. So I tried making changes in the CSV and imported again and again I fell into the duplicate entries error because partial data was already processed from last transaction.
User will not search and remove the partially processed data from the csv rather, he would correct the same csv and import it again since he assumes that last process ended in error

Expected: A process should be either be totally completed or totally rejected (follow the atomic transaction property).  Partial processing and errors at the same time creates confusion on the user part because he has no idea that which data was processed and which caused error. He has to manually edit the csv file to remove processed entries and correct erroneous entries  .

![image](https://user-images.githubusercontent.com/33607689/89554339-5be33900-d82c-11ea-8dc8-127884fde0eb.png)

**Comment by ChitraQA** [comment]
Deferred for later builds.
