### ISSUE TITLE
Admin -> School settings page - Invalid year value is getting submitted successfully for Year 

### ISSUE THREAD

**Issue by ChitraQA** [MontbitTech/WebApp-e-EdPort-LMS#21]
1 Log in as an Admin
2. Click on School Settings.
3. Click in "Edit" under "Action" for the value of the Year.
4.  Enter an invalid value to the field "123456" 
5.  Click on the "Submit' button.

**Actual Result: Year value saved successfully.
Expected Result: User should be prompted to input a valid year value.**
![image](https://user-images.githubusercontent.com/68022354/86947115-faff0d00-c168-11ea-9ab0-b47955643dcb.png)
![image](https://user-images.githubusercontent.com/68022354/86947174-0f430a00-c169-11ea-8c56-1fd023096014.png)

**Comment by montbit-tech** [comment]
@vickyjodha Year selection UI might help here.

**Comment by krtrthbilory** [comment]
fixed. by me
