### ISSUE TITLE
Admin -> Teacher -> Edit Teacher -> Invalid name/ only numbers (1234567) is submitted successfully as Teacher name.

### ISSUE THREAD

**Issue by ChitraQA** [MontbitTech/WebApp-e-EdPort-LMS#23]
"1. Click on Teacher
2. Edit any teacher -> EDIT teacher page shows up
3. Edit with an invalid teacher name as 1234567

**Actual: 1234567 is getting saved successfully
Expected:  Admin should be prompted to input Alphabet characters**
![image](https://user-images.githubusercontent.com/68022354/86953537-3225ec00-c172-11ea-958f-1436b813e60a.png)

**Comment by krtrthbilory** [comment]
this same is happening in add teacher also fixing that too
