### ISSUE TITLE
Admin -> The back button of the E -Learning page is broken (doesn't work)

### ISSUE THREAD

**Issue by ChitraQA** [MontbitTech/WebApp-e-EdPort-LMS#26]
1. Log in to LMS with Admin credentials
2. Click on the back button on the top left corner of the page

**Actual: Button is broken.
Expected: Back button should be clickable and active**

![image](https://user-images.githubusercontent.com/68022354/86954502-b4fb7680-c173-11ea-9bdd-6b1df24146c7.png)

**Comment by krtrthbilory** [comment]
what it should do ?

**Comment by montbit-tech** [comment]
Actually, Let's remove the button from there. It won't serve any useful purpose. Earlier, it was there to collapse the menu.
@krtrthbilory @ChitraQA

**Comment by montbit-tech** [comment]
@vickyjodha Can you please remove that back button from the admin UI?

**Comment by krtrthbilory** [comment]
add one more thing in this bug itself when I click on E-Learning icon on the header right besides this back button it takes me to  /admin/ which is login screen so it should go to /admin/dashboard
