### ISSUE TITLE
After getting an error message on the Add student details page, clicking on back shows the same error message again

### ISSUE THREAD

**Issue by ChitraQA** [MontbitTech/WebApp-e-EdPort-LMS#27]
"1. Admin > Student > Add Student -> Enter invalid / valid values and hit Submit.
2. Error message or success message displayed then vanishes.
3. Click on the back button on the browser's toolbar
"

**Actual: The same error message is shown twice: Once when I click on submit, 2nd when I click on the back button from the browser.
Expected: On clicking back, the Student list page should be displayed **

**Comment by krtrthbilory** [comment]
can't reproduce it

**Comment by montbit-tech** [comment]
Needs a lot of rework. Will be considered in next build.
