### ISSUE TITLE
Admin -> Error messages should not vanish off in few seconds without any action.

### ISSUE THREAD

**Issue by ChitraQA** [MontbitTech/WebApp-e-EdPort-LMS#28]
Error/success messages on all the pages should be displayed like a notification which should have the following :

1. A close button on the right top of the message frame, 
2. Only on clicking the close button, the error message can be closed.
3. A proper text explaining the error or the success message.

**Invalid error message illustration:**
![image](https://user-images.githubusercontent.com/68022354/86956688-1ec94f80-c177-11ea-8093-c56d35a6f6ce.png)

**an example of a Valid error message**
![image](https://user-images.githubusercontent.com/68022354/86956297-7e732b00-c176-11ea-8154-0079f11ef672.png)

**Comment by krtrthbilory** [comment]
anshuman has fixed this also
