### ISSUE TITLE
Issue with Examination portal

### ISSUE THREAD

**Issue by Anjan62** [MontbitTech/WebApp-e-EdPort-LMS#485]
I noticed that the marks are coming in the negative numbers. When the teacher is assigning the marks for the particular question, the teacher is also able to assign the marks in negative and it shouldn't. 

Expected: The assigned marks should start from 1

![image](https://user-images.githubusercontent.com/65858265/95869005-87345800-0d88-11eb-98c0-b3afd672d350.png)

**Comment by krtrthbilory** [comment]
fixed

**Comment by Anjan62** [comment]
Remove 0 also. A question cannot have 0 marks.

**Comment by krtrthbilory** [comment]
done
