### ISSUE TITLE
Duration in exam portal

### ISSUE THREAD

**Issue by Anjan62** [MontbitTech/WebApp-e-EdPort-LMS#486]
I noticed that the duration in the examination portal which is to be filled in minutes is again going in negative numbers. Which shouldn't

Expected: It should at least start from 1.

![image](https://user-images.githubusercontent.com/65858265/95872635-a1703500-0d8c-11eb-9638-5b458e3f7721.png)

**Comment by krtrthbilory** [comment]
fixed

**Comment by Anjan62** [comment]
> fixed

Great to hear that.
