### ISSUE TITLE
Multiple sections in the same class have a same exam case

### ISSUE THREAD

**Issue by Anjan62** [MontbitTech/WebApp-e-EdPort-LMS#491]
I noticed that whenever a teacher is creating an exam, He or she is restricted to create an exam for a particular section one at a time. There might be a case where a teacher wants to take exams for all the sections of the same classes. In that case they wouldn't able to do so.

Expected: Instead of a drop-down list. We could have a checklist or multiple select options for the teachers. So that they can create an exam for all the sections in one go.

![image](https://user-images.githubusercontent.com/65858265/95956000-4a657100-0e1b-11eb-92c4-9f27784bf507.png)

**Comment by krtrthbilory** [comment]
there is a assign option which can be used to assign same exam with same question to another class

**Comment by Anjan62** [comment]
But even that is not working.

**Comment by krtrthbilory** [comment]
workinng fine now
