### ISSUE TITLE
Examination: Show button is showing some error

### ISSUE THREAD

**Issue by Anjan62** [MontbitTech/WebApp-e-EdPort-LMS#492]
I noticed that whenever I am clicking on the show button, after creating an exam. It is showing some error. In such cases, teachers will not be able to see the exam again after creating it once.

Expected: Show button should work and the teacher should get a proper detail of whatever exam they had created

![image](https://user-images.githubusercontent.com/65858265/95957205-096e5c00-0e1d-11eb-958c-15854295f77c.png)

**Comment by krtrthbilory** [comment]
working nnow
