### ISSUE TITLE
Examination: Issue with registered Email-ID 

### ISSUE THREAD

**Issue by Anjan62** [MontbitTech/WebApp-e-EdPort-LMS#493]
What am I supposed to fill out in the registered email id option? I have tried  teacherone@schooltimes-s.ca as a registered id but it is not working. Do help me out if there is anything else and if not then please fix the issue as soon as possible

![image](https://user-images.githubusercontent.com/65858265/95958614-04aaa780-0e1f-11eb-9904-36205709cba9.png)

**Comment by krtrthbilory** [comment]
class's any student's mail id for which the exam have desiged

**Comment by Anjan62** [comment]
ok
