### ISSUE TITLE
Domain specification is considering only Gmail

### ISSUE THREAD

**Issue by Anjan62** [MontbitTech/WebApp-e-EdPort-LMS#502]
I noticed that only Gmail is working in the domain specification. Whenever we are adding a new student.

Expected: Every domain especially the famous one yahoo, Orkut should work. Generally, the college provides its own mail address and wants a registration with ID only. In such a case, our email part will not work

![image](https://user-images.githubusercontent.com/65858265/96090834-700b7c80-0ee6-11eb-94dc-64833d0a305e.png)

**Comment by krtrthbilory** [comment]
our whole product revolves around google's classroom which does't take any other id than gmail so this is not a bug or can't be done in this product

**Comment by Anjan62** [comment]
So without Gmail id, it will not work in any case?

**Comment by krtrthbilory** [comment]
yupp only gmail works

**Comment by Anjan62** [comment]
But generally, college student doesn't prefer to give their personal Email-ID's on such a system. Saying by my personal experience. All the colleges have their own special domain.

**Comment by krtrthbilory** [comment]
but that's our limitation ... I can't help you with this .... they need a google account to login to classroom

**Comment by Anjan62** [comment]
okay. Will talk to aman sir on this once.
