### ISSUE TITLE
Details of the teacher in admin

### ISSUE THREAD

**Issue by Anjan62** [MontbitTech/WebApp-e-EdPort-LMS#507]
I think we should ask for the full name of the teacher instead of just a name. Because it is going to be the id initials. So just for the better enhancement and standard. I think we should ask for a full name. 

![image](https://user-images.githubusercontent.com/65858265/96287849-244cf600-1000-11eb-9746-74ea52f4d84f.png)

**Comment by krtrthbilory** [comment]
they already add full name there
