### ISSUE TITLE
Exam portal issue

### ISSUE THREAD

**Issue by Anjan62** [MontbitTech/WebApp-e-EdPort-LMS#513]
I noticed that a teacher have a compulsion to add 4 option. What if the question is of only true or false or maybe yes or no. 

Expected: Two options button should be enabled. 

![image](https://user-images.githubusercontent.com/65858265/96634804-a4dd6080-1338-11eb-9b19-351d0005aa69.png)

**Comment by Anshumanshrivastava** [comment]
fixed
