### ISSUE TITLE
New assignment issue

### ISSUE THREAD

**Issue by Anjan62** [MontbitTech/WebApp-e-EdPort-LMS#516]
I noticed that whenever the teacher is opening the add assignment option. Points are showing for the particular topic

Expected: It would be better if we use word Marks in the place of Points as it is an assignment

![image](https://user-images.githubusercontent.com/65858265/96636301-bc1d4d80-133a-11eb-9353-8ab3dec4b43f.png)

**Comment by krtrthbilory** [comment]
in google classroom this stated as point so if we give this option as marks it will create confusion so let it be

**Comment by Anjan62** [comment]
okay
