### ISSUE TITLE
Assignment attach file issue

### ISSUE THREAD

**Issue by Anjan62** [MontbitTech/WebApp-e-EdPort-LMS#518]
I noticed that whenever we are clicking on the attach file option in the new assignment tab. It is directly creating the exam.

Expected: A proper space for the attachment of the file should be given in the new assignment tab itself or after clicking on the create and submit assignment a pop-up should open for the submission of file.

![image](https://user-images.githubusercontent.com/65858265/96637620-8da07200-133c-11eb-97ad-3367663d001e.png)

**Comment by krtrthbilory** [comment]
expected behaviour that create ad attach file open a popup window with classroom in it you need click edit option to upload file we can't upload a file into google classroom from api

**Comment by Anjan62** [comment]
But this needs to be mentioned.

**Comment by Anjan62** [comment]
You can't expect this from user

**Comment by krtrthbilory** [comment]
it is in the demo and there is note to allow popup. we are not selling this to everyone only the school subscribe for this can use our system. and there is a whole demo planned for all the teacher about how to use also there is some videos that gets shared with concerned people

**Comment by Anjan62** [comment]
Will discuss this issue on the call once.
