### ISSUE TITLE
Issue with assign button

### ISSUE THREAD

**Issue by Anjan62** [MontbitTech/WebApp-e-EdPort-LMS#519]
I noticed that the assign button is not working. It is simply redirecting to the upper date and time.

Expected: A pop-up window should appear asking for the change in date and time and a reason which should be send to all students as a notice.

![image](https://user-images.githubusercontent.com/65858265/96680536-5315f400-1393-11eb-8a24-64459498f1b9.png)

**Comment by krtrthbilory** [comment]
that's expected behaviour there the teacher could go back and forth and make changes whatever he want and create exam

**Comment by Anjan62** [comment]
But instead of changing the date and time for that particular exam a new exam is used to be created. Which is again a bug. Considering me as a user now my job will be to assign a new exam then delete the previous one and then share a notice to all the students. Which is again a samething as creating a new exam. Hope you are getting me

**Comment by krtrthbilory** [comment]
nope assign always creates another exam which is fine cause there can be one exam per classroom exam name will be same for both ad you don't need to share anything that happens automatically also you don't need to delete anything as you can see every exam is mapped to a classroom this new one will be mapped to the other classroom. I think you better take a demo from someone about the whole system

**Comment by Anjan62** [comment]
Let's discuss this on the call.
