### ISSUE TITLE
Button issue

### ISSUE THREAD

**Issue by Anjan62** [MontbitTech/WebApp-e-EdPort-LMS#520]
Instead of the text format for the delete, show and assign. It should be in the button format. To avoid confusion. As whenever i'm opening the website in the mobile phone it is not clear that wheater it is a text or a button. 

Expected: We can simply give a button look to all that 3 actions. To make it more clear.

![image](https://user-images.githubusercontent.com/65858265/96680830-de8f8500-1393-11eb-9940-93315b676494.png)

**Comment by vickyjodha** [comment]
fixed
