### ISSUE TITLE
Pariksha tab issue

### ISSUE THREAD

**Issue by Anjan62** [MontbitTech/WebApp-e-EdPort-LMS#521]
I noticed that whenever I am opening the exam link. On the upper header instead of my name {User} is written. I guess something is not correct at the coding part. Please look into that urgently

Expected: Whom so ever student registered for the particular exam instead of {User} his name should come or else the initials which he is using while registering in the pariksha for ex- Student registered mail-id is anjan@gmail.com. Anjan can be the user

![image](https://user-images.githubusercontent.com/65858265/96681488-f6b3d400-1394-11eb-9107-d4258aa20ea4.png)

**Comment by Anshumanshrivastava** [comment]
fixed
