### ISSUE TITLE
After Logging out issue

### ISSUE THREAD

**Issue by Anjan62** [MontbitTech/WebApp-e-EdPort-LMS#525]
I noticed that whenever we are signing out of any portal admin or teacher. The the logging button for the same used to be vanished for sometime, till you didn't refresh the page 3-4 times it didn't appear.

Expected: whenever a teacher or admin is logging out, automatically a same page should appear which he used to login. 

![IMG-20201020-WA0015.jpg](https://user-images.githubusercontent.com/65858265/97168858-286ed580-17af-11eb-9ba0-193e6c3a5061.jpg)

**Comment by krtrthbilory** [comment]
if you logout from teacher only teacher login button will appear if you logout from admin only admin will appear considering teacher can't have access to teacher and vice versa
