### ISSUE TITLE
Feedback box issue

### ISSUE THREAD

**Issue by Anjan62** [MontbitTech/WebApp-e-EdPort-LMS#526]
I noticed that the feedback box in the Pariksha portal is unable. We can write in the box

Expected: Feedback Textbox should enable and the user should be able to give the feedback.

![image](https://user-images.githubusercontent.com/65858265/97283987-80b4de80-1866-11eb-98fc-a66fea4b3939.png)

**Comment by krtrthbilory** [comment]
this is not user's feedback this is proctor's feedback ad in our case the system itself is the proctor please start exam and then try exiting full screen mode you'll understand

**Comment by Anjan62** [comment]
Got that. But then what about the above window mentioned in the Screenshot below. If I am not wrong proctor's feedback is coming below the Proctor feedback heading as mentioned.

![image](https://user-images.githubusercontent.com/65858265/97434591-3d7d6d00-1945-11eb-812c-906baf4e7584.png)

**Comment by krtrthbilory** [comment]
your face appears there please start the exam and you'll see your current video there

**Comment by Anjan62** [comment]
I was in the exam mode only.

![image](https://user-images.githubusercontent.com/65858265/97437749-ef1e9d00-1949-11eb-8282-5d56b5076ce6.png)

**Comment by krtrthbilory** [comment]
your video is not on or something. it comes like this
<img width="1440" alt="Screenshot 2020-10-28 at 6 24 29 PM" src="https://user-images.githubusercontent.com/67820106/97438555-f6927600-194a-11eb-98b2-d8fc81f727bb.png">

**Comment by Anjan62** [comment]
okay.
