### ISSUE TITLE
Pariksha portal issue

### ISSUE THREAD

**Issue by Anjan62** [MontbitTech/WebApp-e-EdPort-LMS#529]
I noticed that whenever a student is redirecting on the pariksha portal after signing into it. At the top leftmost corner of the website, where the logo of the school/college is present, there a user is getting a chance to click upon and whenever he/she is clicking on that, it is simply redirecting it to the error page.

Expected: Two things can be done, first: A user shouldn't get option to click over there or if that's mean something then that error page shouldn't it will actually create confusion for the user.

![image](https://user-images.githubusercontent.com/65858265/97391298-eb1c5c00-1904-11eb-9268-3a031534b626.png)

**Comment by krtrthbilory** [comment]
fixed
