### ISSUE TITLE
Exam portal UI issue

### ISSUE THREAD

**Issue by Anjan62** [MontbitTech/WebApp-e-EdPort-LMS#532]
Just the enhancement needed. Note that in the exam portal whenever I am clicking on the Rightmost instruction tab the content in the middle or on the main screen shifted adjust itself so that it is readable and visible while it is opened. As mentioned in the first screenshot. 
On the other hand, when I am opening the leftmost feedback tab the center doesn't adjust itself, although the last word of the sentence tries to adjust itself, again come back to its original position as mentioned in the second screenshot.

SS-1
![image](https://user-images.githubusercontent.com/65858265/97436677-5fc4ba00-1948-11eb-8138-0bd1e6aa228d.png)

SS-2
![image](https://user-images.githubusercontent.com/65858265/97436802-9569a300-1948-11eb-96bd-ac3bea2b977b.png)

**Comment by krtrthbilory** [comment]
as discussed not a issue
