### ISSUE TITLE
Android Emulator UI issue

### ISSUE THREAD

**Issue by Anjan62** [MontbitTech/WebApp-e-EdPort-LMS#535]
I noticed that the logo for the report is not appearing. Kindly check.

Expected: Like other proper logo for the same should be visible

![image](https://user-images.githubusercontent.com/65858265/97579960-b6012e00-1a18-11eb-966b-3a4c717076e4.png)

**Comment by krtrthbilory** [comment]
maybe your internet's issue

**Comment by Anjan62** [comment]
Nope i am connected with a 100Mbps wifi connection. And android version is also latest. Kindly check it again.

**Comment by krtrthbilory** [comment]
unable to reproduce kindly use your mobile phone to test or set responsiveness devices in your web browser and report if you get this on your mobile phone

**Comment by Anjan62** [comment]
Checked showing the same :/

**Comment by krtrthbilory** [comment]
paste your screenshot for the same

**Comment by Anjan62** [comment]
Automatically fixed. LOL, sorry my bad.
