### ISSUE TITLE
UI issue for Android Emulator in exam portal

### ISSUE THREAD

**Issue by Anjan62** [MontbitTech/WebApp-e-EdPort-LMS#536]
I noticed that question add button and random text area are clashing, kindly make it properly aligned.

![image](https://user-images.githubusercontent.com/65858265/97580705-ac2bfa80-1a19-11eb-80ee-60e81f4fb3d7.png)

**Comment by krtrthbilory** [comment]
@vickyjodha set your system to iphone 6/7/8 this problem is on those devices only

**Comment by vickyjodha** [comment]
fixed
