### ISSUE TITLE
UI Issue

### ISSUE THREAD

**Issue by Anjan62** [MontbitTech/WebApp-e-EdPort-LMS#547]
Just an enhancement. In the examination portal when we are creating the questions, two times the options are written. PFA the screenshot for the same, Which is not looking good. Either we can remove the option from the text bar or the option written just above it. 

![image](https://user-images.githubusercontent.com/65858265/98156995-a7c27e80-1efe-11eb-8844-08d5c1abbdc4.png)

**Comment by vickyjodha** [comment]
fixed
