### ISSUE TITLE
UI issue in the android emulator

### ISSUE THREAD

**Issue by Anjan62** [MontbitTech/WebApp-e-EdPort-LMS#549]
Just an enchantment, whenever we are creating an exam, the examination name is coming one space back which is again not looking good. Proper alignment is required between the text bar below the examination name and text examination name.
PFA the screenshot for the same.

![image](https://user-images.githubusercontent.com/65858265/98157800-e3117d00-1eff-11eb-8421-bbe88a397102.png)

**Comment by vickyjodha** [comment]
fixed
