### ISSUE TITLE
Issue with the assignment tab

### ISSUE THREAD

**Issue by Anjan62** [MontbitTech/WebApp-e-EdPort-LMS#555]
The team noticed that whenever we are creating a new assignment for students and clicking on the create button, the assignment is forwarding to all the students. But what if the case where the teacher wants to send the assignment only to few students. 

Expected: Either we can have a drop-down menu containing all the student's names of that particular class or before sending it to all the students. Or as we have in the classroom option where the instruction of the assignment is present we can use that. 

Just the problem simply on clicking the create button assignment is going to each and every student.

![image](https://user-images.githubusercontent.com/65858265/98240041-dbe58000-1f8e-11eb-9ec4-cde41f397b0c.png)

**Comment by krtrthbilory** [comment]
it doesn't work that way google's classroom doesn't have any feature like that the assignment goes to whole class also it almost never happens that teacher would give assignment to some and not others and there is sections just for this if anyone wanna differentiate between students in same class ca create a section. please discuss with concerned people about any new feature before posting it

**Comment by Anjan62** [comment]
Already concerned, I guess you didn't get me. I'll once discuss this on-call.

**Comment by krtrthbilory** [comment]
concerned who is going to implement this and that's me
