### ISSUE TITLE
Mandatory fields

### ISSUE THREAD

**Issue by Anjan62** [MontbitTech/WebApp-e-EdPort-LMS#560]
I noticed while adding a new institution the fields which need to be mandatory to the users are not mandatory. Kindly make it mandatory options for the users

![image](https://user-images.githubusercontent.com/65858265/101898100-904b7500-3bd1-11eb-91a3-12f05c75f652.png)

**Comment by krtrthbilory** [comment]
they are not users this is admin it supposed to be us

**Comment by Anjan62** [comment]
Checked and verified.
