### ISSUE TITLE
Mobile no. digits

### ISSUE THREAD

**Issue by Anjan62** [MontbitTech/WebApp-e-EdPort-LMS#561]
I noticed that while creating a new institution, the User can enter any digits of the number. It should only limit to 10 digits.

![image](https://user-images.githubusercontent.com/65858265/101898404-12d43480-3bd2-11eb-8fb4-627057427c1f.png)

**Comment by vickyjodha** [comment]
fixed

**Comment by Anjan62** [comment]
Checked
