### ISSUE TITLE
UI-Spelling Mistake

### ISSUE THREAD

**Issue by Anjan62** [MontbitTech/WebApp-e-EdPort-LMS#563]
In the same field, where we are collecting the details for the institution. In the address bar, the spelling of the address is wrong. Please rectify it asap. It gives a negative impact on users. PFA the screenshot for the same.

![image](https://user-images.githubusercontent.com/65858265/101899461-defa0e80-3bd3-11eb-964f-ab2e2acbe1b6.png)

**Comment by vickyjodha** [comment]
fixed

**Comment by Anjan62** [comment]
Checked
