### ISSUE TITLE
Issue with phone no. field

### ISSUE THREAD

**Issue by Anjan62** [MontbitTech/WebApp-e-EdPort-LMS#564]
I noticed that on the phone no. field, while adding a new institution it is also accepting the phone no. which are not valid. I mean it is also accepting alphabets. Kindly check the issue. This bug can give a negative impact on users. PFA the screenshot for the same

![image](https://user-images.githubusercontent.com/65858265/101899964-b0306800-3bd4-11eb-8984-6cd35c0e67ed.png)

**Comment by vickyjodha** [comment]
fixed

**Comment by Anjan62** [comment]
Checked
