### ISSUE TITLE
Issue with Email field

### ISSUE THREAD

**Issue by Anjan62** [MontbitTech/WebApp-e-EdPort-LMS#565]
I noticed that in the email field while adding the new institution. An invalid domain name is also accepted by the field. Kindly check.
PFA the screenshot for the same

![image](https://user-images.githubusercontent.com/65858265/101900248-2f25a080-3bd5-11eb-909c-513491c17791.png)

**Comment by vickyjodha** [comment]
fixed

**Comment by Anjan62** [comment]
Checked
