### ISSUE TITLE
Issue in the Question tab

### ISSUE THREAD

**Issue by Anjan62** [MontbitTech/WebApp-e-EdPort-LMS#569]
I noticed that even after creating the class in the class tab, and then in the question tab while adding the class, In the drop-down menu it is not showing anything. Kindly check it once. Correct me if I am doing anything wrong here. I have tried but I am unable to bring it in the question tab.
For any confusion, kindly check the Screenshot.

![image](https://user-images.githubusercontent.com/65858265/101902121-24203f80-3bd8-11eb-91f2-920411dcfc25.png)

**Comment by krtrthbilory** [comment]
there is no question so the filters are not appearing resolve this too

**Comment by Anjan62** [comment]
Okay. Closing this issue.
