### ISSUE TITLE
Incomplete Subject details

### ISSUE THREAD

**Issue by Anjan62** [MontbitTech/WebApp-e-EdPort-LMS#571]
In the subject tab, where we are asking for the subject name. I guess we also need to ask for the chapter name and topic name in the same column. That whole part is missing from here. If it is added somewhere else, I'll suggest you put that information also here. As we don't have a separate tab for chapter and topic name. PFA the ss for the same

![image](https://user-images.githubusercontent.com/65858265/101948256-b72c9a00-3c17-11eb-883f-7b400ba9c7c2.png)

**Comment by krtrthbilory** [comment]
there won't be any topic or chapter will be just like this we don't know who's gonna put what topic so topic or chapter everything will be only on question level also not a high priority or critical or it could b categorised as a bug it should be your personal suggestion please resolve as it is totally fine

**Comment by Anjan62** [comment]
Sure thing. Changing the label

**Comment by krtrthbilory** [comment]
resolve this as there is no issues here

**Comment by Anjan62** [comment]
okay
