### ISSUE TITLE
Issue in User Interface in Student portal 

### ISSUE THREAD

**Issue by Anjan62** [MontbitTech/WebApp-e-EdPort-LMS#572]
I noticed that in the student portal. Where students are allowed to analyze their exams. There is an issue with the Welcome screen. PFA the screenshot you will get it better. Either only Welcome should be written or Welcome and then user name not specifically 'User'

![image](https://user-images.githubusercontent.com/65858265/101949206-3d95ab80-3c19-11eb-88a2-f83e48311d4b.png)

**Comment by krtrthbilory** [comment]
fixed ... removed this as this feature is not available currently

**Comment by Anjan62** [comment]
Checked
