### ISSUE TITLE
Two times the same tab.

### ISSUE THREAD

**Issue by Anjan62** [MontbitTech/WebApp-e-EdPort-LMS#574]
I noticed in the student portal, we have two strengths and weaknesses tab. Kindly check and make the necessary changes. PFA the screenshot for the same.
The first tab is working correctly and redirecting the strength and weakness column. But the last tab is directly showing the error 404 messages. Kindly check

![image](https://user-images.githubusercontent.com/65858265/101950132-c52fea00-3c1a-11eb-9582-51c122472093.png)

**Comment by krtrthbilory** [comment]
fixed removed this as this feature is ot available currently

**Comment by Anjan62** [comment]
Checked.
