### ISSUE TITLE
Center Alignment issue

### ISSUE THREAD

**Issue by Anjan62** [MontbitTech/WebApp-e-EdPort-LMS#575]
I noticed that in the student profile tab, A student details are coming in the left corner and the other space is blank whereas in the teacher portal and main admin portal. Profile used to come in the center. Kindly make the relevant changes, just an enhancement.
PFA the ss for the same.

![image](https://user-images.githubusercontent.com/65858265/101950820-e8a76480-3c1b-11eb-8732-22b72eefd864.png)

**Comment by vickyjodha** [comment]
fixed

**Comment by Anjan62** [comment]
Checked.
